version: 2.1
jobs:
  build_ix:
    docker:
      - image: tweakoz/ubuntu_builders:eoan8
    resource_class: large
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: ./ork.build/bin/init_env.py --create ./.staging --command "./build.py --ez"
  build_osx:
    macos:
      xcode: 11.3.0
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: ./ork.build/bin/obt.osx.installdeps.py
      - run: ./ork.build/bin/init_env.py --create ./.staging --command "./build.py --ez"
workflows:
  version: 2
  build: # name of your workflow
    jobs:
      - build_ix
      - build_osx
