# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.15'
  steps:
  - checkout: self
    fetchDepth: 50
    submodules: true
  - script: |
      echo "HomeBrew setup"
      ./ork.build/bin/obt.osx.installdeps.py
    displayName: 'HomeBrew setup'
  - script: |
      echo "Init Orkid Build Container"
      ./ork.build/bin/init_env.py --create $(Agent.BuildDirectory)
    displayName: 'Init Orkid Build Container'
    
    
    
