version: 2.1
jobs:
  build:
    docker:
      - image: tweakoz/ubuntu_builders:eoan6
    resource_class: xlarge
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: ./ork.build/bin/init_env.py --create ./.staging --command "./build.py --ez"
